server:
  port: 9003
embedded:
  zookeeper:
    port: 2181
chenyh:
  service:
    version: 1.0.0
dubbo:
  application:
    name: iWorld
  registry:
    address: zookeeper://127.0.0.1:${embedded.zookeeper.port}
  consumer:
    check: false

#spring:
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: test-consumer-group
#      enable-auto-commit: false
#      auto-commit-interval: 1000
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer